top_users: 5
nick: Kitbot
server: irc.freenode.org
channels:
- '#kitinfo'
date_format: '%d.%m.%Y'
time_format: '%d.%m.%Y %H:%M'
stats_url: http://dtun.de:4567/?channel=%s
source_url: https://github.com/niklasb
database: sqlite://db/kitbot.sqlite3
