source :rubygems
gem "nokogiri"
gem "pry"
gem "feedjira"
gem "mechanize"
gem "sequel"
gem "sqlite3"
gem "sinatra"
gem "sinatra-contrib"
gem "thin"
gem "json"
gem "haml"
gem "eventmachine"
gem "dynamic_binding", :git => "git://github.com/niklasb/ruby-dynamic-binding.git"
gem "websocket-eventmachine-client", :git => "https://github.com/imanel/websocket-eventmachine-client"
